name: Build and Release Executables

on:
  release:
    types: [created]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller pandas numpy openpyxl
      - name: Build executable
        run: pyinstaller --onefile --windowed --hidden-import openpyxl kbart_gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/kbart_gui.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller pandas numpy openpyxl
      - name: Build executable
        run: pyinstaller --onefile --hidden-import openpyxl kbart_gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/kbart_gui

  release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux]
    permissions:
      contents: write
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: ./windows
          
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-executable
          path: ./linux

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./windows/kbart_gui.exe
          asset_name: "kbart_gui-windows.exe"
          asset_content_type: application/octet-stream

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./linux/kbart_gui
          asset_name: "kbart_gui-linux"
          asset_content_type: application/octet-stream
